const infoFields = [
  { name: "firstName", label: "First Name", icon: <User /> },
  { name: "lastName", label: "Last Name", icon: <User /> },
  { name: "email", label: "Email", icon: <Mail /> },
  { name: "phone", label: "Phone", icon: <Phone /> },
  {
    name: "gender",
    label: "Gender",
    icon: <User />,
    type: "select",
    options: ["Male", "Female", "Other"],
  },
  { name: "dob", label: "Date of Birth", icon: <Calendar />, type: "date" },
  {
    name: "maritalStatus",
    label: "Marital Status",
    icon: <Heart />,
    type: "select",
    options: ["Single", "Married", "Divorced"],
  },
  { name: "zip", label: "Zipcode", icon: <MapPin /> },
  { name: "address", label: "Address", icon: <Landmark /> },
  { name: "aadhaarOrPan", label: "Aadhaar No", icon: <IdCard /> },
  {
    name: "employment",
    label: "Employment Status",
    icon: <Briefcase />,
    type: "select",
    options: ["Employed", "Unemployed", "Self-Employed", "Student", "Retired"],
  },
  { name: "occupation", label: "Occupation", icon: <Briefcase /> },
  {
    name: "annualIncome",
    label: "Annual Income",
    icon: <DollarSign />,
    type: "number",
  },
];
